["Visual Settings"]
	#Enable emissive rendering for glowing mushrooms and plants
	enableEmissiveRendering = true
	#Enable falling leaves and petals particles for trees
	enableLeavesParticles = true
	#Enable falling petals particles for hanging flowers (e.g. Wisteria)
	enableHangingFlowersParticles = true
	#Enable Night Blossom spores particles
	enableNightBlossomParticles = true
	#Enable Hybiscus spores particles
	enableHybiscusParticles = true
	#Enable Swamp Moonpuff fireflies particles
	enableSwampMoonpuffParticles = true
	#Let Swamp Moonpuff fireflies spawn only at night
	enableSwampMoonpuffNightOnly = true
	#Enable Emberfall Blossom spores particles
	enableEmberfallParticles = true

[Potions]
	#Enable the use of Green Amanita in Poison and Long Poison potions
	enableAmanitaPoison = true
	#Enable the use of Bog Glimmer in Leaping potion
	enableBogGlimmerLeaping = true
	#Enable the use of Twilight Bark Shroom in Regeneration potion
	enableTwilightRegeneration = true
	#Enable the use of Pale Ghostling in Invisibility potion
	enableGhostlingInvisibility = true
	#Enable the use of Night Blossom in Slow Falling potion
	enableNightBlossomSlowFalling = true
	#Enable the use of Emberfall Flower in Fire Resistance potion
	enableEmberfallFireResistance = true
