ServerEvents.compostableRecipes(event=>{
    //event.add("bamboo", 0.125) // 12.5% to increase compost progress

    let toCompost = [
    'meadow:delphinium',
    'meadow:saxifrage',
    'meadow:enzian',
    'meadow:fire_lily',
    'meadow:eriophorum',
    'meadow:eriophorum_tall',
    'meadow:alpine_poppy',
    'minecraft:dead_bush',
    'minecraft:bamboo',
    'quark:chorus_weeds',
    'quark:chorus_twist',
    'minecraft:chorus_plant',
    'minecraft:chorus_flower',
    'the_bumblezone:crystalline_flower',
    'minecraft:chorus_fruit',
    'minecraft:poisonous_potato' ,
    'mysticsbiomes:spring_bamboo',
    'moresnifferflowers:ambush_seeds',
    'moresnifferflowers:dragonfly',
    'moresnifferflowers:dyespria',
    'moresnifferflowers:bonmeelia_seeds',
    'thaumon:greatwood_leaves',
    'thaumon:silverwood_leaves',
    'meadow:pine_leaves',
    'netherdepthsupgrade:warped_kelp_block',
    'netherdepthsupgrade:warped_kelp_carpet_block',
    'netherdepthsupgrade:crimson_kelp',
    'netherdepthsupgrade:crimson_seagrass',
    'netherdepthsupgrade:crimson_kelp_block',
    'netherdepthsupgrade:crimson_kelp_carpet_block',
    'netherdepthsupgrade:warped_kelp',
    'netherdepthsupgrade:warped_seagrass',
    'regions_unexplored:ashen_grass',
    'regions_unexplored:glistering_fern',
    'regions_unexplored:glistering_bloom',
    'regions_unexplored:hyacinth_flowers',
    'regions_unexplored:hyacinth_bloom',
    'regions_unexplored:tall_hyacinth_stock',
    'regions_unexplored:ashen_shrub',
    'regions_unexplored:blue_bioshroom_block',
    'regions_unexplored:glowing_blue_bioshroom_block',
    'regions_unexplored:green_bioshroom_block',
    'regions_unexplored:glowing_green_bioshroom_block',
    'regions_unexplored:pink_bioshroom_block',
    'regions_unexplored:glowing_pink_bioshroom_block',
    'regions_unexplored:yellow_bioshroom_block',
    'regions_unexplored:glowing_yellow_bioshroom_block',
    'regions_unexplored:saguaro_cactus',
    'serene_shrubbery:peach_foxglove',
    'serene_shrubbery:purple_foxglove',
    'serene_shrubbery:white_foxglove',
    'serene_shrubbery:sunset_foxglove',
    'serene_shrubbery:fireweed',
    'serene_shrubbery:hydrangea',
    'serene_shrubbery:purple_hydrangea',
    'serene_shrubbery:red_hydrangea',
    'serene_shrubbery:white_hydrangea',
    'serene_shrubbery:orange_crown_cactus',
    'serene_shrubbery:pink_crown_cactus',
    'serene_shrubbery:red_pansies',
    'serene_shrubbery:yellow_pansies',
    'serene_shrubbery:white_pansies',
    'serene_shrubbery:orange_pansies',
    'serene_shrubbery:pink_pansies',
    'serene_shrubbery:purple_pansies',
    'serene_shrubbery:twinflower',
    'serene_shrubbery:blue_liverwort',
    'serene_shrubbery:purple_liverwort',
    'serene_shrubbery:white_liverwort',
    'serene_shrubbery:purple_lupine',
    'serene_shrubbery:lupine_pink',
    'serene_shrubbery:lupine_white',
    'serene_shrubbery:butterfly_bush'
    ];
    
    for (const compost of toCompost) {
        event.add(compost, 0.125);
  }

})