ClientEvents.lang("en_us", event => {
event.renameItem('architects_palette:dripstone_bricks', 'Dripstone Tiles')
event.renameItem('architects_palette:dripstone_brick_stairs', 'Dripstone Tile Stairs')
event.renameItem('architects_palette:dripstone_brick_slab', 'Dripstone Tile Slab')
event.renameItem('architects_palette:dripstone_brick_wall', 'Dripstone Tile Wall')
event.renameItem('architects_palette:dripstone_brick_vertical_slab', 'Dripstone Tile Vertical Slab')

event.renameItem('architects_palette:tuff_bricks', 'Tuff Tiles')
event.renameItem('architects_palette:tuff_pillar', 'Tuff Pillar')
event.renameItem('architects_palette:tuff_brick_stairs', 'Tuff Tile Stairs')
event.renameItem('architects_palette:tuff_brick_wall', 'Tuff Tile Wall')
event.renameItem('architects_palette:tuff_brick_slab', 'Tuff Tile Slab')
event.renameItem('architects_palette:tuff_brick_vertical_slab', 'Tuff Tile Vertical Slab')

event.renameItem('quark:calcite_pillar', 'Calcite Pillar')
event.renameItem('architects_palette:calcite_pillar', 'Calcite Patterned Pillar')

event.renameItem('quark:dripstone_pillar', 'Dripstone Pillar')
event.renameItem('architects_palette:dripstone_pillar', 'Dripstone Tiled Pillar')

event.renameItem('dawnoftimebuilder:cobbled_limestone', 'Cobbled Pale Limestone')
event.renameItem('dawnoftimebuilder:cobbled_limestone_edge', 'Cobbled Pale Limestone Edge')
event.renameItem('dawnoftimebuilder:cobbled_limestone_plate', 'Cobbled Pale Limestone Plate')
event.renameItem('dawnoftimebuilder:cobbled_limestone_slab', 'Cobbled Pale Limestone Slab')
event.renameItem('dawnoftimebuilder:limestone_bricks', 'Pale Limestone Bricks')
event.renameItem('dawnoftimebuilder:limestone_bricks_edge', 'Pale Limestone Bricks Edge')
event.renameItem('dawnoftimebuilder:limestone_bricks_plate', 'Pale Limestone Bricks Plate')
event.renameItem('dawnoftimebuilder:limestone_bricks_slab', 'Pale Limestone Bricks Slab')
event.renameItem('dawnoftimebuilder:limestone_bricks_wall', 'Pale Limestone Bricks Wall')
event.renameItem('dawnoftimebuilder:limestone_baluster', 'Pale Limestone Baluster')
event.renameItem('dawnoftimebuilder:limestone_sided_column', 'Pale Limestone Sided Column')
event.renameItem('dawnoftimebuilder:limestone_gargoyle', 'Pale Limestone Gargoyle')
event.renameItem('dawnoftimebuilder:limestone_chimney', 'Pale Limestone Chimney')
event.renameItem('dawnoftimebuilder:limestone_fireplace', 'Pale Limestone Fireplace')

event.renameItem('quark:framed_glass', 'Clear Framed Glass') 
event.renameItem('quark:framed_glass_pane', 'Clear Framed Glass Pane')

event.renameItem('dawnoftimebuilder:sandstone_bricks', 'Sandstone Tiles')
event.renameItem('dawnoftimebuilder:sandstone_bricks_plate', 'Sandstone Tiles Plate')
event.renameItem('dawnoftimebuilder:sandstone_bricks_slab', 'Sandstone Tiles Slab')
event.renameItem('dawnoftimebuilder:sandstone_bricks_edge', 'Sandstone Tiles Edge')
event.renameItem('dawnoftimebuilder:sandstone_bricks_wall', 'Sandstone Tiles Wall')
event.renameItem('dawnoftimebuilder:sandstone_bricks_turquoise_pattern', 'Sandstone Tiles Turquoise Pattern')
event.renameItem('dawnoftimebuilder:sandstone_bricks_turquoise_pattern_plate', 'Sandstone Tiles Turquoise Pattern Plate')
event.renameItem('dawnoftimebuilder:sandstone_bricks_turquoise_pattern_slab', 'Sandstone Tiles Turquoise Pattern Slab')
event.renameItem('dawnoftimebuilder:sandstone_bricks_turquoise_pattern_edge', 'Sandstone Tiles Turquoise Pattern Edge')
event.renameItem('dawnoftimebuilder:sandstone_bricks_turquoise_pattern_wall', 'Sandstone Tiles Turquoise Pattern Wall')
event.renameItem('dawnoftimebuilder:sandstone_bricks_stairs', 'Sandstone Tiles Stairs')
event.renameItem('dawnoftimebuilder:sandstone_bricks_turquoise_pattern_stairs', 'Sandstone Tiles Turquoise Pattern Stairs')

event.renameItem('betterend:ender_dust', 'End Powder')
event.renameItem('twilightforest:wrought_iron_fence', 'Simple Wrought Iron Fence')
event.renameItem('betterend:end_stone_brick_cracked', 'Very Cracked End Stone Bricks')
event.renameItem('thaumon:amber', 'Amber Lamp')

event.renameItem('betterend:amber_block', 'End Amber Block')
event.renameItem('betterend:raw_amber', 'Raw End Amber')
event.renameItem('betterend:amber_gem', 'End Amber Gem')
event.renameItem('betterend:amber_ore', 'End Amber Ore')
event.renameItem('ae2:quartz_glass', 'Resonant Quartz Glass')
event.renameItem('ae2:quartz_vibrant_glass', 'Vibrant Resonant Quartz Glass')
event.renameItem('cluttered:blueberry_muffin', 'Decorative Blueberry Muffin')
event.renameItem('environmental:bluebell', 'Fairy Bluebell')
event.renameItem('cluttered:willow_vines', 'Dusky Willow Vines')
event.renameItem('hexerei:willow_vines', 'Witch Willow Vines')

event.renameItem('decorative_blocks:cherry_beam', 'Cherry Support Beam')
event.renameItem('decorative_blocks:dark_oak_beam', 'Dark Oak Support Beam')
event.renameItem('decorative_blocks:warped_beam', 'Warped Support Beam')
event.renameItem('decorative_blocks:oak_beam', 'Oak Support Beam')
event.renameItem('decorative_blocks:spruce_beam', 'Spruce Support Beam')
event.renameItem('decorative_blocks:mangrove_beam', 'Mangrove Support Beam')
event.renameItem('decorative_blocks:birch_beam', 'Birch Support Beam')
event.renameItem('decorative_blocks:acacia_beam', 'Acacia Support Beam')
event.renameItem('decorative_blocks:crimson_beam', 'Crimson Support Beam')
event.renameItem('decorative_blocks:jungle_beam', 'Jungle Support Beam')
event.renameItem('furniture:cash_register', 'Basic Cash Register')
event.renameItem('tanukidecor:cash_register', 'Deluxe Cash Register')
event.renameItem('tanukidecor:cuckoo_clock', 'Cute Cuckoo Clock')
event.renameItem('tanukidecor:hourglass', 'Decorative Hourglass')
event.renameItem('furniture:coffer', 'Simple Coffer')

})