#Blacklist of block IDs ignored by the scanner and blueprints (example: ["minecraft:stone", "minecraft:dirt"] )
blacklistBlocks = []
#Set the MaxScannerBlockCount gamerule
maxscannerblockcount = 30000
#Enable maxScannerBlockCount server config
enable_maxscannerblockcount = false
#Add a link to the tablet home page
tablet_social_1 = ""
#Add a link to the tablet home page
tablet_social_2 = ""
#Add a link to the tablet home page
tablet_social_3 = ""
#Add a link to the tablet home page
tablet_social_4 = ""
#Add a link to the tablet home page
tablet_social_5 = ""
