#Show the developer manual in the book selector (disable for player modpacks)
show_dev_manual = true

#Mob sound settings for the guide book
[sounds]
	#Format: 'mob_id=sound_id'. You can use either the short name ('creeper') or the full ID ('minecraft:creeper')
	custom_mob_sounds = ["creeper=entity.creeper.primed", "iron_golem=entity.iron_golem.damage", "snow_golem=entity.snow_golem.shoot", "axolotl=entity.axolotl.idle_air", "turtle=entity.turtle.egg_crack", "slime=entity.slime.squish", "magma_cube=entity.magma_cube.squish", "cave_spider=entity.spider.ambient", "trader_llama=entity.llama.ambient", "bee=entity.bee.loop", "ender_dragon=entity.ender_dragon.growl", "cod=entity.cod.flop", "salmon=entity.salmon.flop", "tropical_fish=entity.tropical_fish.flop", "pufferfish=entity.pufferfish.blow_out"]
